export const API = {
  auth: "",
  eventDetails: "",
  order: "",
  casino: "",
};

export const Settings = {
  paymentIntent: "",
  otp: "",
  casino: "",
  siteTitle: "",
  forceLogin: "",
  registration: "",
  demoLogin: "",
  withdraw: "",
  deposit: "",
  siteUrl: "",
  balanceApiLoop: "",
  disabledDevtool: "",
  casinoCurrency: "",
  interval: "",
  logoFormat: "",
  logoHeight: "",
  logoWidth: "",
  apkLink: "",
  betFairCashOut: "",
  registrationWhatsapp: "",
  build: "",
  mac88: "",
  aura: "",
  referral: "",
  b2c: "",
  slotWolf: "",
  liveCasinoWolf: "",
  auraWolf: "",
  language: "",
  otpless: "",
  lobby: "",
};
